version: "3.8"

services:
  # DNS сервер
  coredns:
    image: coredns/coredns:latest
    container_name: smartdns-coredns
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./coredns:/etc/coredns:ro
    command: -conf /etc/coredns/Corefile
    networks:
      - smartdns
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # SNI Proxy - используем проверенный образ
  sniproxy:
    image: vimagick/sniproxy
    container_name: smartdns-sniproxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./sniproxy/sniproxy.conf:/etc/sniproxy.conf:ro
    networks:
      - smartdns
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  smartdns:
    driver: bridge
