version: '3.8'

services:
  # DNS сервер - обрабатывает DNS запросы и перенаправляет нужные домены на SNI Proxy
  coredns:
    image: coredns/coredns:latest
    container_name: smartdns-coredns
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./coredns:/etc/coredns:ro
    command: -conf /etc/coredns/Corefile
    networks:
      - smartdns
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # SNI Proxy - прозрачно проксирует HTTPS трафик на основе SNI
  sniproxy:
    image: mosajjal/sniproxy:latest
    container_name: smartdns-sniproxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./sniproxy/config.yaml:/config.yaml:ro
    networks:
      - smartdns
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  smartdns:
    driver: bridge
